#!/usr/bin/env ruby
conf ="/home/dokku/#{ARGV[0]}/nginx.conf"
puts "conf=#{conf}"
domain = `dokku config:get #{ARGV[0]} DOMAIN`
puts "domain=#{domain}"

if ( domain && File.exists?(conf))
 conf_content = File.read(conf) 
  /server_name (.*);/.match(conf_content)
  new_server_name = "#{domain} #{$1}"
 conf_content.gsub!($1,new_server_name)
 File.delete(conf)
  File.open(conf, "w") { |file| file.write conf_content}
  `sudo /etc/init.d/nginx reload > /dev/null`  
  puts "#{domain} has been added!"
else
  puts "can not find #{conf}" unless File.exists? (conf)
  puts "no domain specified!" unless ENV['DOMAIN']
end


  
