#!/usr/bin/env ruby
conf ="#{ENV['DOKKU_ROOT']}/#{ENV['APP']}/nginx.conf"

puts "load nginx.conf from #{conf}"

if File.exists? "#{ENV['DOKKU_ROOT']}/#{ENV['APP']}/.domain"
  puts "add #{domain}"
else
  puts "no domain specified, using #{ENV['APP']}.#{ENV['VHOST']}"
end